version: "2"

services:
    php:
        volumes:
            - '.:/srv'
        environment:
            - SYMFONY_ENV=dev

    front:
        ports:
            - 0.0.0.0:8080:80
        volumes_from:
            - php

    database:
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
        driver: local